### ISSUE TITLE
Project Setup and Dry Run

### ISSUE THREAD

**Issue by AzhanBuzt** [AzhanBuzt/KiranaBazaar#2]
@Madan-M-Singhal : Project setup need to be done and Dry run of project.

**Comment by AzhanBuzt** [comment]
@Madan-M-Singhal this need to be achieved by max 13-March-2019. Project and tag has been updated for reference.

**Comment by AzhanBuzt** [comment]
@Pranshu4308 Assignee Updated in the task.

**Comment by AzhanBuzt** [comment]
**Team** - When this will be get completed, task are awaited in Assigned To Dev Pipeline.

**Comment by Madan-M-Singhal** [comment]
I will continue from tomorrow onwards.

**Comment by Madan-M-Singhal** [comment]
Successfully Configured project setup and executed all scenario's into my machine. Hence closing !
