### ISSUE TITLE
Explicit Wait need to be implemented wherever required

### ISSUE THREAD

**Issue by AzhanBuzt** [AzhanBuzt/KiranaBazaar#3]
@AzhanBuzt @Madan-M-Singhal 
Primary focus is to replace Thread.sleep from code logics and implement explicit wait so that it could work flawlessly across all device at any internet network.

**Comment by AzhanBuzt** [comment]
@Madan-M-Singhal - I would analyse the position where we can implement this explicit wait and list it here  asap.

**Comment by Madan-M-Singhal** [comment]
Screenshot code has been edited to support  on multiple file system and task has been merged.

**Comment by AzhanBuzt** [comment]
Issue has been closed successfully
