### ISSUE TITLE
Verify the validation of pin code at registration activity of kirana bazaar

### ISSUE THREAD

**Issue by AzhanBuzt** [AzhanBuzt/KiranaBazaar#8]
**Description**: Implementation is required to validate the possible scenario for pin code.

- [x] Capture Dynamic pin code if possible for DDU(**Deen Dayal Upadhyay** Junction) as app only has service for **DDU** previously named as mughal-sarai.
- [x] Verify that proper length of pin code is only allowed.
- [x] Implement logic that pin code other than DDU is not allowed at registration.

**Comment by AzhanBuzt** [comment]
@Madan-M-Singhal - Any Update?

**Comment by Madan-M-Singhal** [comment]
i have to find out the test case for this issue then i will able to start.

**Comment by AzhanBuzt** [comment]
Explore the application & implement whatever is possible , stage is yours

**Comment by Madan-M-Singhal** [comment]
> Explore the application & implement whatever is possible , stage is yours

**Comment by Madan-M-Singhal** [comment]
fg

**Comment by AzhanBuzt** [comment]
@Madan-M-Singhal : Issue can only be closed when it successfully merged in master.

**Comment by AzhanBuzt** [comment]
@Madan-M-Singhal : I have found an API for dynamic postal codes of India, can we implement this after pin code is validated as positive and allowed to be entered in edittext, we could implement one code level check that if its belong to DDU then permissible unless bypass the test code as not serviceable area? 
Api- **http://postalpincode.in/api/pincode/211016**

**Comment by AzhanBuzt** [comment]
@Madan-M-Singhal - Validation of positive and negative **_PinCodes_** has been completed and merged , fetching data from API has been done & _**JsonParsing**_ is left which will be delivered in next PR for this issue.
![image](https://user-images.githubusercontent.com/48254269/54637543-e1870d00-4aae-11e9-859b-f866063a7230.png)

**Comment by AzhanBuzt** [comment]
Completed closing the issue. Merged with master.
